### ISSUE TITLE
Send icons are changing even if not send

### ISSUE THREAD

**Issue by solinco** [mamont77/faktura#2]
The send icon (Green check) or not send icon (Red cross), changes when saving the invoice and the checkbox "Send kopi?" is checked. It shall only change to send icon when its actually send. it's not possible to change clint in the dropdown when editing and saving.

**Comment by mamont77** [comment]
Martin, sorry. It seems I did not understand.
Example: 
![screensnap - solinco - solinco v 1 75 - google chrome - odesk 06-24-2015 14 35 22](https://cloud.githubusercontent.com/assets/970967/8328984/594a11ee-1a7e-11e5-9c83-1ae3da6f9cfc.png)
The status of this icon can be changed here
![solinco v 1 75 - google chrome 06-24-2015 14 36 57](https://cloud.githubusercontent.com/assets/970967/8329004/86060788-1a7e-11e5-8d9d-97112cb92894.png)
These data are stored in the database.
![localhost solinco invoice - heidisql portable 9 1 0 4867 06-24-2015 14 38 20](https://cloud.githubusercontent.com/assets/970967/8329028/bd7e8a50-1a7e-11e5-8c75-370d9ca2177a.png)

Can you explain in other words, what should I do?

**Comment by mamont77** [comment]
Also i can't add CC email, the field is disabled. How it should work?
![solinco v 1 75 - google chrome 06-24-2015 14 39 50](https://cloud.githubusercontent.com/assets/970967/8329066/fc51b73e-1a7e-11e5-96de-5f1d380b3ccb.png)

**Comment by solinco** [comment]
No, there are no checkbox saying ”Sendt”, so please make one after “Send kopi?”

De venligste hilsner,

Martin Hansson

Fra: Ruslan [mailto:notifications@github.com]
Sendt: 24. juni 2015 13:39
Til: mamont77/faktura
Cc: Martin Hansson - Solinco
Emne: Re: [faktura] Send icons are changing even if not send (#2)


Martin, sorry. It seems I did not understand.
Example:
[screensnap - solinco - solinco v 1 75 - google chrome - odesk 06-24-2015 14 35 22]<https://cloud.githubusercontent.com/assets/970967/8328984/594a11ee-1a7e-11e5-9c83-1ae3da6f9cfc.png>
The status of this icon can be changed here
[solinco v 1 75 - google chrome 06-24-2015 14 36 57]<https://cloud.githubusercontent.com/assets/970967/8329004/86060788-1a7e-11e5-8d9d-97112cb92894.png>
These data are stored in the database.
[localhost solinco invoice - heidisql portable 9 1 0 4867 06-24-2015 14 38 20]<https://cloud.githubusercontent.com/assets/970967/8329028/bd7e8a50-1a7e-11e5-8c75-370d9ca2177a.png>

Can you explain in other words, what should I do?

**Comment by mamont77** [comment]
If I understood correctly. If the mail was sent once, the icon should remain green forever. And if the mail had not been sent never, the icon has a red. Is it right? If true, you can check.

**Comment by solinco** [comment]
I cant click the Send kopi? Checkbox http://virt.solinco.dk/solinco/faktura/index.php?indhold=invoice&side=rediger&id=636

De venligste hilsner,

Martin Hansson

Fra: Ruslan [mailto:notifications@github.com]
Sendt: 25. juni 2015 08:26
Til: mamont77/faktura
Cc: Martin Hansson - Solinco
Emne: Re: [faktura] Send icons are changing even if not send (#2)


If I understood correctly. If the mail was sent once, the icon should remain green forever. And if the mail had not been sent never, the icon has a red. Is it right? If true, you can check.

**Comment by solinco** [comment]
And it hassent been sent

De venligste hilsner,

Martin Hansson

Fra: Ruslan [mailto:notifications@github.com]
Sendt: 25. juni 2015 08:26
Til: mamont77/faktura
Cc: Martin Hansson - Solinco
Emne: Re: [faktura] Send icons are changing even if not send (#2)


If I understood correctly. If the mail was sent once, the icon should remain green forever. And if the mail had not been sent never, the icon has a red. Is it right? If true, you can check.

**Comment by mamont77** [comment]
>>And it hassent been sent

Do you mean you have not received an mail? I will create a company with my email addresses and check it.

By the way, do you get mails in a live site (solinco.dk/faktura/index.php)? Maybe it depends on the server configuration.

**Comment by solinco** [comment]
You are adding invoices to the production site!

De venligste hilsner,

Martin Hansson

Fra: Ruslan [mailto:notifications@github.com]
Sendt: 25. juni 2015 08:46
Til: mamont77/faktura
Cc: Martin Hansson - Solinco
Emne: Re: [faktura] Send icons are changing even if not send (#2)


And it hassent been sent

Do you mean you have not received an mail? I will create a company with my email addresses and check it.

By the way, do you get mails in a live site (solinco.dk/faktura/index.php)? Maybe it depends on the server configuration.

**Comment by mamont77** [comment]
I think it fixed. Ready for testing.

**Comment by mamont77** [comment]
Also.. i created the new field in DB. After the transfer the site to production I will create a field in a live database. Just ping me.

**Comment by mamont77** [comment]
Did discussed in Skype.
Please test again.

**Comment by solinco** [comment]
works perfect now :-)

**Comment by mamont77** [comment]
Good news. Please test other.
25 июня 2015 г. 22:23 пользователь "solinco" <notifications@github.com>
написал:

**Comment by solinco** [comment]
I think its it, everything works ☺

De venligste hilsner,

Martin Hansson

Fra: Ruslan [mailto:notifications@github.com]
Sendt: 25. juni 2015 21:26
Til: mamont77/faktura
Cc: Martin Hansson - Solinco
Emne: Re: [faktura] Send icons are changing even if not send (#2)

Good news. Please test other.
25 июня 2015 г. 22:23 пользователь "solinco" <notifications@github.com<mailto:notifications@github.com>>
написал:

**Comment by solinco** [comment]
Now we just need to do the switch to live site

De venligste hilsner,

Martin Hansson

Fra: Ruslan [mailto:notifications@github.com]
Sendt: 25. juni 2015 21:26
Til: mamont77/faktura
Cc: Martin Hansson - Solinco
Emne: Re: [faktura] Send icons are changing even if not send (#2)

Good news. Please test other.
25 июня 2015 г. 22:23 пользователь "solinco" <notifications@github.com<mailto:notifications@github.com>>
написал:
