### ISSUE TITLE
Send kopi checkbox is not saving check

### ISSUE THREAD

**Issue by solinco** [mamont77/faktura#4]
When saving the invoice and the checkbox "Send kopi?" is checked, the check is not saved when I open it again

**Comment by mamont77** [comment]
Ready for testing.

**Comment by solinco** [comment]
http://virt.solinco.dk/solinco/faktura/index.php?indhold=invoice&side=rediger&id=640

when unchecking ”Send kopi” and save, then open the item again and check ”Send kopi?”, then the send icon turns green

De venligste hilsner,

Martin Hansson

Fra: Ruslan [mailto:notifications@github.com]
Sendt: 24. juni 2015 13:27
Til: mamont77/faktura
Cc: Martin Hansson - Solinco
Emne: Re: [faktura] Send kopi checkbox is not saving check (#4)


Ready for testing.

**Comment by mamont77** [comment]
Martin,

How it works now. Step by step.

1. Edit any invoice, for example http://virt.solinco.dk/solinco/faktura/index.php?indhold=invoice&side=rediger&id=640

![solinco v 1 75 - google chrome 06-25-2015 08 13 37](https://cloud.githubusercontent.com/assets/970967/8347706/208cc7f4-1b12-11e5-9863-edfe0e1faae6.png)

2. Check/uncheck "Send kopi?"

3. Save (Gem faktura).

4. Edit again, the system remember the last status for "Send kopi?".

The title of the task is "Send kopi checkbox is not saving check".

Does it work correctly now?

Or is it should work differently?

**Comment by mamont77** [comment]
I got it. I am going add a new field in database.

**Comment by solinco** [comment]
No, it still doesn’t work correctly.

When I click “Send kopi?” on and off, it works ok, but the send icon changes to green even though it hasn’t been send

I added mh@solinco.dk<mailto:mh@solinco.dk> in the Cc field under client Venari, and the field “Send kopi?” should only be active when an email is present in the field Cc

**Comment by mamont77** [comment]
One question.
Then you create copy of invoice, should this status be inherited or be empty?

**Comment by solinco** [comment]
Everything should be inherited when copying

De venligste hilsner,

Martin Hansson

Fra: Ruslan [mailto:notifications@github.com]
Sendt: 25. juni 2015 07:48
Til: mamont77/faktura
Cc: Martin Hansson - Solinco
Emne: Re: [faktura] Send kopi checkbox is not saving check (#4)


One question.
Then you create copy of invoice, should this status be inherited or be empty?

**Comment by mamont77** [comment]
Please test again.

1. Edit any invoice, for example http://virt.solinco.dk/solinco/faktura/index.php?indhold=invoice&side=rediger&id=640
2. Check/uncheck "Send kopi?"
3. Save (Gem faktura).
4. Edit again, the system remember the last status for "Send kopi?".
5. Try make copy of invoice, the state of the checkbox should be copied.

Do not pay attention to the icons. It #2 works separately and independently.

**Comment by mamont77** [comment]
>>I cant click the Send kopi? Checkbox http://virt.solinco.dk/solinco/faktura/index.php?indhold=invoice&side=rediger&id=636

It has been fixed on javascript side.
